apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: other/adot-instrumentation
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - checkout
              - key: app.kubernetes.io/component  
                operator: In
                values:
                - service                  
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: checkout 
        env:
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: ENDPOINTS_HTTP_KEEPALIVE
          value: "false"
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OTEL_INSTRUMENTATION_HTTP_SERVER_CAPTURE_REQUEST_HEADERS
          value: traceparent,tracestate
